# Reto número 1 (Información de cheque)
print("********** PROGRAMA PARA LA GENERACIÓN DE CHEQUES **********")
fecha = input("Por favor ingrese la fecha (aaaa-mm-dd): ")
monto_numerico = float(input("Por favor ingrese el valor del cheque en números: "))
monto_en_letras = input("Por favor ingrese el valor del cheque en letras: ")
nombre_beneficiario = str(input("Por favor ingrese el nombre del beneficiario: "))
firma = input("Por favor ingrese nombre para la firma: ")

print("********** INFORMACIÓN PARA EL CHEQUE **********")
print("Fecha: "+fecha)
print("Valor: "+str(monto_numerico))
print("Valor en letras: "+str(monto_en_letras))
print("A nombre de: "+nombre_beneficiario)
print("Firma: "+str(firma))